### PR TITLE
* [ios]  fix issue that rotate(0) not work after rotate(>180degree)

### LINKED ISSUE #2070: 关于animation的一个问题
在测试animation的时候发现一个问题，ios版本的(最新sdk)翻转动画，如果转动角度超过180度，只能顺时针，不能逆时针，180度内正反转都没问题，超过之后反转没有任何动作，例如下面代码
```
<template>
    <div style="justify-content: center; align-items: center">
        <div id="target" onclick="{{doAnim}}"
             style="width: 240px; height: 240px; background-color: #F0AD4E;justify-content: center; align-items: center;">
            <text style="text-align: center;color: white;font-size: 80px">Click</text>
        </div>
    </div>
</template>
<script>
    module.exports = {
        data: {
            rotate : '0deg'
        },
        methods: {
            doAnim: function () {
                var self = this;
                var animation = require('@weex-module/animation');
                var target = this.$el('target');
                self.rotate = self.rotate === '0deg' ? '270deg' : '0deg';
                var options = {
                    styles: {
                        transform: 'rotate(' + self.rotate + ')',
                    },
                    duration: 1000,
                };
                var callback = function () {
                    nativeLog('animation complete.');
                };
                animation.transition(target, options, callback);
            }
        }
    }
</script>
```
在0-270的时候是正常的，270-0的时候不动，再到0-270的时候，会突然从270调到0再开始0-270。我在android上测试是正常的，不知道是不是bug？

### PR DESCRIPTION
**Pull request by cxfeng1**
* fix #2070

### CODE REVIEW

File: ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m [hunk 1]
```diff
@@ -12,6 +12,32 @@
...
+}
+
+- (void)setWx_finishBlock:(void (^)())wx_finishBlock
+{
+    [self setValue:wx_finishBlock forKey:kAnimationCompletionBlock];
+}
+
+@end
+
+@interface WXAnimationModule () <CAAnimationDelegate>
```
Comment (acton393) [inline ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m]: maybe iOS 10 later ?
